"""Release B: the specialist team's findings after the fictional measurement year.

Everything written here is SYNTHETIC case data for SLOP4761. The "measured year"
(April 2027 to March 2028) is generated by running each home's EXISTING condition
through the scenario model on a perturbed year, so that every monthly table, the
tank levels, the bills and the memo reconcile with one another. It is not a record of
any real household, and one year of it establishes nothing about drought reliability:
that is what the separate synthetic dry year (make_datasets.py) is for.

Three kinds of climate data are kept apart on the site and in the files:
  * sourced long-term climate: Bureau of Meteorology monthly statistics [S39];
  * the synthetic measured year: this module, seeded and reproducible;
  * the synthetic dry-year stress test: make_datasets.py.

Specialists analyse; they do not choose the system. The memo reports conditions,
uncertainty and implications, and leaves the design decision to the student.

Run:  python release_b.py   -> ../../src/data/release-b.json and
                               ../../public/data/release-b/<home>/*.csv
"""

import csv
import json
import math
import os
import random
import sys

import site_model as sm
import scenario as sc
from case import HOMES, BY_SID, totals

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
OUT_JSON = os.path.join(REPO, "src", "data", "release-b.json")
OUT_DIR = os.path.join(REPO, "public", "data", "release-b")

MEMO_DATE = "2028-04-14"
YEAR_LABEL = "April 2027 to March 2028"
CAL = [3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2]          # calendar month index of measured months
LABELS = ["Apr 2027", "May 2027", "Jun 2027", "Jul 2027", "Aug 2027", "Sep 2027", "Oct 2027",
          "Nov 2027", "Dec 2027", "Jan 2028", "Feb 2028", "Mar 2028"]
ISO = ["2027-04", "2027-05", "2027-06", "2027-07", "2027-08", "2027-09", "2027-10", "2027-11",
       "2027-12", "2028-01", "2028-02", "2028-03"]

TEAM = [
    ("Dr Mara Quinlan", "water systems and hydraulics"),
    ("Tomasz Ferreira", "soils and horticulture"),
    ("Aisha Rahman", "monitoring, data quality and records"),
]

# Seasonal shape of indoor use in the measured year, normalised to a mean of 1.0 so the
# year matches the course's 150 L/person/day convention. Order: calendar Jan..Dec.
SEASON = {
    "S1": [1.06, 1.05, 1.02, 0.99, 0.97, 0.95, 0.95, 0.96, 0.98, 1.00, 1.03, 1.04],
    "S2": [1.08, 1.07, 1.04, 0.99, 0.95, 0.93, 0.93, 0.95, 0.99, 1.02, 1.05, 1.00],
    "S3": [1.04, 1.04, 1.02, 1.00, 0.98, 0.97, 0.97, 0.97, 0.99, 1.00, 1.02, 1.00],
    "S4": [1.07, 1.06, 1.02, 0.99, 0.96, 0.95, 0.95, 0.96, 0.98, 1.00, 1.03, 1.03],
    "S5": [1.02, 1.01, 1.00, 0.99, 0.97, 0.96, 0.96, 0.98, 1.00, 1.05, 1.06, 1.00],
}

# Where the house's highest served fixture sits relative to the tank outlet, from the
# specialists' level survey, and what was observed at the fixtures. Case data.
HYDRAULICS = {
    "S1": dict(tank_outlet_rl=100.75, fixture="laundry tap", fixture_rl=101.85, garden_high_rl=101.15,
               fixtures={"shower": 8.6, "basin": 4.8, "kitchen tap": 6.9, "toilet cistern refill": 7.2,
                         "washing machine fill": 10.8, "garden hose": 14.5},
               served_now="garden tap (gravity)", pressure_note="Mains pressure at the laundry tap 52 m head static; the tank's gravity tap delivers under 1 m of head and could not run a sprinkler."),
    "S2": dict(tank_outlet_rl=100.25, fixture="ensuite shower rose", fixture_rl=102.35, garden_high_rl=100.40,
               fixtures={"shower": 9.1, "ensuite shower": 8.4, "basin": 5.2, "kitchen tap": 7.4,
                         "toilet cistern refill": 7.0, "washing machine fill": 11.5, "drip zone (shade house)": 6.2,
                         "drip zone (fruit block)": 7.8},
               served_now="whole house and drip, through the existing pressure pump",
               pressure_note="Existing pump cuts in at 20 m and out at 34 m of head; the drip zones run off the same pump."),
    "S3": dict(tank_outlet_rl=100.05, fixture="first-floor toilet cistern", fixture_rl=103.65, garden_high_rl=100.20,
               fixtures={"shower (first floor)": 8.2, "basin": 4.6, "kitchen tap": 6.5,
                         "toilet cistern refill (ground)": 6.8, "toilet cistern refill (first floor)": 6.8,
                         "washing machine fill": 9.6},
               served_now="garden tap (gravity)",
               pressure_note="The ground-floor and first-floor WCs both have external-wall cisterns; the first-floor cistern is about 3.6 m above the tank outlet."),
    "S4": dict(tank_outlet_rl=100.55, fixture="laundry tap", fixture_rl=101.60, garden_high_rl=100.90,
               fixtures={"shower": 9.4, "bath": 14.0, "basin": 5.0, "kitchen tap": 7.1,
                         "toilet cistern refill": 7.4, "washing machine fill": 11.2, "drip line (beds)": 5.6},
               served_now="two garden taps through the 0.4 kW pump",
               pressure_note="The WC cistern's inlet is on the east external wall, 0.9 m above the floor, so a rainwater line can reach it without opening an internal wall."),
    "S5": dict(tank_outlet_rl=100.30, fixture="shower rose (elevated floor)", fixture_rl=105.40, garden_high_rl=100.10,
               fixtures={"shower": 9.0, "ensuite shower": 8.8, "basin": 5.0, "kitchen tap": 7.3,
                         "toilet cistern refill": 7.1, "washing machine fill": 12.0, "micro-spray zone": 18.0},
               served_now="whole house and garden, through the existing pressure pump",
               pressure_note="The floor is 3.1 m above ground. The micro-spray zone and the house share the pump, and pressure at the shower drops noticeably when the zone runs."),
}

# Growing-zone findings. Relative productivity is the specialists' synthesis of sun,
# soil and competition; the scenario model uses the same values (case.zone_quality).
SOILS = {
    "S1": {
        "G1": dict(texture="clay loam", ph=6.1, ec=0.08, oc=1.9, no3=12, p=28, depth=45, sun_s=10.5, sun_w=2.5, note="house shadow covers the bed from May to August"),
        "G2": dict(texture="clay loam", ph=6.3, ec=0.09, oc=1.6, no3=9, p=22, depth=40, sun_s=6.0, sun_w=3.0, note="morning sun only"),
        "G3": dict(texture="clay loam, compacted", ph=6.0, ec=0.07, oc=2.2, no3=8, p=18, depth=35, sun_s=11.0, sun_w=6.5, note="lawn; compaction to 150 mm"),
        "G4": dict(texture="sandy clay loam", ph=6.6, ec=0.12, oc=3.4, no3=24, p=55, depth=60, sun_s=11.5, sun_w=7.0, note="best soil; the raised beds are here"),
        "G5": dict(texture="clay loam", ph=6.4, ec=0.10, oc=2.6, no3=15, p=35, depth=50, sun_s=9.0, sun_w=5.0, note="shade from the fruit trees"),
        "G6": dict(texture="clay loam", ph=5.6, ec=0.06, oc=1.4, no3=4, p=12, depth=20, sun_s=5.5, sun_w=2.0, note="eucalypt roots dense at 200 mm; afternoon shade"),
    },
    "S2": {
        "G1": dict(texture="sandy loam", ph=7.9, ec=0.45, oc=0.9, no3=18, p=30, depth=60, sun_s=12.0, sun_w=8.5, note="shadecloth transmits about 45 per cent of light after ten years"),
        "G2": dict(texture="loamy sand", ph=8.2, ec=0.62, oc=0.6, no3=10, p=18, depth=80, sun_s=13.0, sun_w=9.0, note="calcium carbonate at depth; emitters scaled"),
        "G3": dict(texture="loamy sand", ph=8.3, ec=0.40, oc=0.7, no3=5, p=10, depth=80, sun_s=10.0, sun_w=6.5, note="tree roots; wind-exposed edge"),
        "G4": dict(texture="sand", ph=8.4, ec=0.35, oc=0.3, no3=3, p=8, depth=90, sun_s=13.5, sun_w=9.5, note="bare; surface temperature above 60 degC in January"),
    },
    "S3": {
        "G1": dict(texture="imported loam over fill", ph=6.8, ec=0.15, oc=2.1, no3=14, p=40, depth=30, sun_s=10.0, sun_w=6.0, note="fill at 300 mm; building rubble at one test hole"),
        "G2": dict(texture="sandy loam over fill", ph=6.5, ec=0.12, oc=2.8, no3=16, p=45, depth=35, sun_s=4.5, sun_w=2.5, note="direct sun until about 11 am"),
        "SG": dict(texture="loam", ph=6.7, ec=0.10, oc=3.0, no3=20, p=50, depth=60, sun_s=11.0, sun_w=7.0, note="common property; scheme tap metered to the body corporate"),
    },
    "S4": {
        "G1": dict(texture="red-brown loam", ph=7.4, ec=0.20, oc=1.8, no3=10, p=30, depth=55, sun_s=11.5, sun_w=6.5, note="full sun"),
        "G2": dict(texture="red-brown loam", ph=7.5, ec=0.22, oc=1.3, no3=6, p=20, depth=40, sun_s=7.0, sun_w=3.0, note="narrow; afternoon sun only"),
        "G3": dict(texture="loam, heavily amended", ph=7.9, ec=0.95, oc=3.9, no3=35, p=90, depth=50, sun_s=11.0, sun_w=6.0, note="salinity elevated after decades of mains irrigation"),
        "G4": dict(texture="red-brown loam", ph=7.6, ec=0.30, oc=2.0, no3=12, p=28, depth=55, sun_s=9.5, sun_w=5.5, note="tree shade; the almond is mostly dead"),
        "G5": dict(texture="red-brown loam", ph=7.3, ec=0.18, oc=2.4, no3=14, p=34, depth=60, sun_s=12.0, sun_w=7.5, note="best aspect"),
    },
    "S5": {
        "G1": dict(texture="sandy loam", ph=5.9, ec=0.05, oc=1.5, no3=8, p=12, depth=70, sun_s=11.0, sun_w=10.0, note="waterlogs briefly after the heaviest storms"),
        "G2": dict(texture="sandy clay loam", ph=6.0, ec=0.06, oc=2.0, no3=11, p=16, depth=80, sun_s=11.5, sun_w=10.5, note="best garden soil on the block"),
        "G3": dict(texture="sandy loam, laterite gravel", ph=5.7, ec=0.04, oc=1.2, no3=5, p=8, depth=40, sun_s=6.0, sun_w=5.0, note="dense mango shade"),
        "G4": dict(texture="sandy loam", ph=5.8, ec=0.05, oc=1.1, no3=6, p=9, depth=60, sun_s=9.0, sun_w=8.0, note="partly under shadecloth"),
    },
}

QUALITY = {
    # (month index into the measured year, source, turbidity NTU, E. coli MPN/100 mL, hardness mg/L CaCO3, TDS mg/L, pH, iron mg/L, note)
    "S1": [(1, "tank T1", 1.2, 0, 18, 45, 6.9, 0.02, "dry spell"), (6, "tank T1", 6.5, 12, 15, 40, 6.7, 0.05, "two days after 38 mm of rain"),
           (9, "tank T1", 2.1, 2, 20, 52, 7.0, 0.03, ""), (6, "mains", 0.3, 0, 45, 90, 7.6, 0.01, "reference sample")],
    "S2": [(0, "tank T1", 1.8, 3, 210, 520, 7.8, 0.10, "tank holds mixed rain and bore water"), (6, "bore", 0.4, 0, 385, 960, 7.6, 0.42, "hardness and iron explain the emitter scale"),
           (9, "tank T1", 4.9, 18, 150, 380, 7.6, 0.06, "after the January storm"), (10, "bore", 0.5, 0, 392, 975, 7.6, 0.40, ""),
           (10, "drip emitter deposit", None, None, None, None, None, None, "white scale, effervesces in acid: calcium carbonate")],
    "S3": [(2, "tank T1", 0.9, 1, 12, 35, 6.6, 0.02, ""), (9, "tank T1", 7.8, 25, 10, 30, 6.5, 0.04, "after 120 mm in a day; first flush absent on this zone"),
           (9, "mains", 0.2, 0, 70, 150, 7.7, 0.01, "reference sample")],
    "S4": [(3, "tank T1", 1.5, 0, 22, 60, 7.1, 0.02, ""), (8, "tank T1", 2.8, 6, 25, 64, 7.0, 0.03, "low tank, warm water"),
           (8, "mains", 0.3, 0, 110, 290, 7.8, 0.01, "reference sample; typical of the metropolitan supply")],
    "S5": [(2, "tank T1", 0.8, 0, 14, 38, 6.6, 0.03, "mid dry season"), (7, "tank T2", 1.1, 2, 12, 36, 6.5, 0.02, ""),
           (9, "tank T1", 12.0, 34, 9, 25, 6.3, 0.08, "wet season, leaf litter in the inlet screen"), (10, "tank T2", 9.5, 20, 10, 28, 6.4, 0.06, "")],
}

MISSING = {
    "S1": [(3, "tank_end_kl", "Tank level logger failed from 9 to 26 July; levels interpolated from two manual dips")],
    "S2": [(10, "rain_mm", "Rain gauge funnel blocked by a grasshopper swarm; February total taken from the Alice Springs Airport station")],
    "S3": [(0, "indoor_kl", "Sub-meters were installed on 18 April; April's end-use split is scaled from May")],
    "S4": [(6, "garden_applied_kl", "Drip-line meter read by the household on paper in October; transcription checked against the mains bill")],
    "S5": [(10, "tank_end_kl", "Logger in tank 1 flooded in February; tank 2's record used for both, which assumes they sit at the same level")],
}

# Recurring-cost and maintenance facts gathered through the year. Case data.
COSTS = {
    "S1": dict(tariff_kwh=0.33, water_usage_kl=3.10, supply_charge_year=740, carting_kl=None,
               maintenance=["Gutters cleaned twice, 3 hours each, both in autumn.", "Compost tumbler turned weekly; about 20 minutes a week in total with feeding."]),
    "S2": dict(tariff_kwh=0.33, water_usage_kl=None, supply_charge_year=0, carting_kl=28.0,
               maintenance=["Drip emitters cleared four times, 2 hours each; two lines replaced.", "Cartridge filter changed every eight weeks, $12 per cartridge.", "Bore pump serviced once, $180."]),
    "S3": dict(tariff_kwh=0.33, water_usage_kl=3.40, supply_charge_year=690, carting_kl=None,
               maintenance=["Tank inlet screen cleared three times after storms.", "Worm farm fed and harvested; about 15 minutes a week."]),
    "S4": dict(tariff_kwh=0.33, water_usage_kl=3.60, supply_charge_year=820, carting_kl=None,
               maintenance=["Pump pressure switch replaced in January, $95.", "Beds mulched twice; about 6 hours each time."]),
    "S5": dict(tariff_kwh=0.33, water_usage_kl=None, supply_charge_year=0, carting_kl=22.0,
               maintenance=["Tank inlet screens cleared monthly in the wet, 30 minutes each.", "Septic pumped out in November, $650, which the household had deferred."]),
}

FOOD_WASTE = {  # kg in each audit week: (total, plant-based, meat and dairy, garden trimmings)
    "S1": [(7.6, 4.6, 1.1, 11.0), (6.9, 4.1, 1.2, 4.0), (7.2, 4.4, 1.0, 6.5), (7.4, 4.5, 1.1, 14.0)],
    "S2": [(7.1, 4.4, 1.0, 5.0), (7.5, 4.6, 1.2, 3.0), (6.8, 4.0, 1.1, 4.5), (7.3, 4.5, 1.0, 7.0)],
    "S3": [(7.0, 4.3, 1.0, 2.5), (7.4, 4.5, 1.1, 2.0), (7.2, 4.4, 1.2, 3.0), (7.1, 4.2, 1.0, 3.5)],
    "S4": [(7.5, 4.6, 1.1, 9.0), (7.0, 4.2, 1.2, 6.0), (7.3, 4.5, 1.0, 12.5), (7.2, 4.4, 1.0, 5.5)],
    "S5": [(7.4, 4.6, 1.0, 18.0), (7.2, 4.4, 1.1, 22.0), (7.1, 4.3, 1.2, 9.0), (7.5, 4.6, 1.1, 12.0)],
}
AUDIT_WEEKS = ["week of 12 July 2027", "week of 11 October 2027", "week of 17 January 2028", "week of 13 March 2028"]

IMPLICATIONS = {
    "S1": [
        "The 5 kL tank on the garage roof filled only in late winter and was empty at the end of {empty_run}; the house roof, almost five times larger, is not connected.",
        "Indoor use was close to the course convention, with toilet and laundry together about a third of it: a steady year-round demand that rainwater could serve if the client wants it to.",
        "Air temperature fell below zero on {frost} nights in the year, nearly all between May and September; anything installed outside needs frost protection or it will not meet the winter-reliability priority.",
        "The herb strip's poor growth is explained by shade and eucalypt roots, not by soil chemistry.",
    ],
    "S2": [
        "Emitter blockage is calcium carbonate scale from hard bore water, not biofilm; the fix is filtration and flushing, not new lines.",
        "Carted water arrived in {loads} loads of 12 kL, mostly between October and March. The bore allocation was fully used, evenly across months, because the bore pump tops up the tank whenever there is room.",
        "Only one of the five guttered roof zones is connected; the other four together are about twice its area.",
        "The tap timer gave the shade-house vegetables and fruit block about {pshare} per cent of the irrigation they needed; from December to February the tank was usually empty by mid-morning.",
    ],
    "S3": [
        "The rear roof plane alone kept the 3 kL tank above half full for most of the year; the tank rarely ran dry because it serves only a garden tap.",
        "Both WC cisterns are on external walls. A rainwater line to them does not require opening walls, but the first-floor cistern sets the pump's static lift.",
        "The rear garden gets direct sun only until about 11 am; the front bed and the shared allocation are the productive ground.",
        "The body corporate secretary has indicated in writing that a slimline tank under 1.8 m on the lot would be considered, and that connecting the front roof plane would need a formal application.",
    ],
    "S4": [
        "The January decline in the beds is water stress compounded by salinity in the vegetable beds, not a nitrogen shortage.",
        "The 5 kL tank on the garage roof ran dry in {empty_run}; the house roof, more than five times larger, sends all its water to the street.",
        "The WC cistern can be supplied from outside, so toilet flushing is available to a rainwater design without opening a wall.",
        "Existing electricity for the garden pump was small; the household's concern about running costs will turn on any new pumps, modules and consumables.",
    ],
    "S5": [
        "The tanks overflowed {over_kl} kL in {over_run} while the household carted water in {cart_run}: a storage timing problem, not a rainfall shortage.",
        "The west roof plane's gutter falls correctly to two downpipe positions; it can be connected without regrading.",
        "Overflow currently scours the ground beside the piers. A test pit south-east of the shed drained a filled 300 mm hole in 55 minutes, so a dispersal point there is plausible.",
        "The micro-spray zone and the house share one pump, and the shower pressure drop when both run is the household's most frequent complaint.",
    ],
}

QUESTIONS = {
    "S1": ["Whether the client would accept rainwater in the laundry if toilet flushing alone does not justify a pump.",
           "How much of the back lawn the children actually use; the 100 m² figure is the client's, not a measurement."],
    "S2": ["Whether the bore allocation could be renewed on the same terms; the licence is reviewed in 2031.",
           "How the family would run a composting toilet during summer heat, which the specialists did not observe."],
    "S3": ["Whether the body corporate would approve a pump enclosure on the side path.",
           "Whether the shared-garden allocation will be renewed at the next annual general meeting."],
    "S4": ["What the family would accept as a manageable winter crop, which the year did not test.",
           "Whether a salinity flush with rainwater before planting would recover the beds in one season."],
    "S5": ["Whether a neighbour could check the system during the July absence, which would change what can be left running.",
           "How long the existing poly tanks will last; both show sun-bleaching on the north side."],
}


def measured_climate(sid: str):
    """A synthetic year: long-term means perturbed with a seeded generator."""
    home = BY_SID[sid]
    base = sc.mean_climate(sid)
    c = sm.load_climate()[home.presets["station"]]
    rng = random.Random(4761 + int(sid[1]))
    f = [min(2.4, max(0.15, math.exp(rng.gauss(0, 0.45)))) for _ in range(12)]
    rain = [base.rain[CAL[i]] * f[i] for i in range(12)]
    target = sum(base.rain) * rng.uniform(0.90, 1.06)
    rain = [round(r * target / sum(rain), 1) for r in rain]
    tmax = [round(c["tmax"][CAL[i]] + rng.gauss(0, 0.7), 1) for i in range(12)]
    tmin = [round(c["tmin"][CAL[i]] + rng.gauss(0, 0.7), 1) for i in range(12)]
    tmean = [(a + b) / 2 for a, b in zip(tmax, tmin)]
    eto = [sm.eto_month(c["lat"], tmax[i], tmin[i], CAL[i]) for i in range(12)]
    d35 = (c.get("d35") or [0] * 13)
    cl = sc.Climate("synthetic measured year", LABELS[:], [sm.DAYS[CAL[i]] for i in range(12)], rain, eto, tmean, tmin)
    cl.gfac = [sm.growing_factor(tmean[i], d35[CAL[i]]) for i in range(12)]
    return cl, tmax, tmin


def run(sid: str) -> dict:
    home = BY_SID[sid]
    ex = sc.existing_choice(home)
    mean_run = sc.evaluate(sid, ex)
    start = next(m for m in mean_run["monthly"] if m["month"] == "Mar")["tank_end"]
    cl, tmax, tmin = measured_climate(sid)
    factors = [SEASON[sid][CAL[i]] for i in range(12)]
    r = sc.evaluate(sid, ex, cl, spinup_years=0, start_level_kl=start, demand_factor=factors)

    rng = random.Random(89 + int(sid[1]))
    c0 = sm.load_climate()[home.presets["station"]].get("d0")
    months = []
    for i, m in enumerate(r["monthly"]):
        split = {u: m["indoor"] * sc.END_USES[u] / 150 for u in sc.INDOOR}
        imported_indoor = m["imported"] - m["garden_mains"] - m["garden_scheme"]
        row = {
            "month": ISO[i], "label": LABELS[i], "days": m["days"],
            "rain_mm": round(m["rain"], 1), "tmax_c": tmax[i], "tmin_c": tmin[i],
            "eto_mm": round(m["eto"]), "roof_inflow_kl": round(m["inflow"], 1),
            "overflow_kl": round(m["overflow"], 1), "tank_end_kl": round(m["tank_end"], 1),
            "indoor_kl": round(m["indoor"], 1),
            "toilet_kl": round(split["toilet"], 2), "shower_basin_kl": round(split["shower"], 2),
            "laundry_kl": round(split["laundry"], 2), "kitchen_kl": round(split["kitchen"], 2),
            "other_kl": round(split["other"], 2),
            "indoor_from_tank_kl": round(m["tank_indoor"], 1),
            "bore_kl": round(m["bore"], 1),
            "imported_kl": round(imported_indoor + m["garden_mains"], 1),
            "garden_applied_kl": round(m["garden_tank"] + m["garden_mains"] + m["garden_grey"] + m["garden_bore"], 1),
            "garden_from_mains_kl": round(m["garden_mains"], 1),
            "garden_unmet_estimate_kl": round(m["garden_unmet"], 1),
            "pump_kwh": round(m["e_pump"] * m["days"], 1),
            "coldest_night_c": round(tmin[i] - rng.uniform(4.5, 7.5), 1),
            "frost_nights": round((c0[CAL[i]] if c0 else 0) * rng.uniform(0.8, 1.2)),
            "quality_flag": "",
        }
        months.append(row)
    for i, field_, note in MISSING[sid]:
        months[i]["quality_flag"] = f"{field_}: {note}"

    t = totals(home)
    connected = r["roof_connected_m2"]
    pb = sum(max(0.0, x["rain_mm"] - 2) for x in months)
    runoff_coeff = sum(x["roof_inflow_kl"] for x in months) * 1000 / (pb * connected) if pb and connected else None
    fw = FOOD_WASTE[sid]
    weekly = sum(x[0] for x in fw) / len(fw)
    hyd = HYDRAULICS[sid]
    lift = round(hyd["fixture_rl"] - hyd["tank_outlet_rl"], 2)
    fixtures = hyd["fixtures"]
    # Ten highest one-minute flow events at the house, built from fixture signatures.
    names = [k for k in fixtures if "zone" not in k and "hose" not in k and "drip" not in k]
    events = []
    ev_rng = random.Random(7 + int(sid[1]))
    for k in range(10):
        n = 3 if k < 2 else 2
        combo = ev_rng.sample(names, n)
        peak = sum(fixtures[c] for c in combo) * ev_rng.uniform(0.9, 1.0)
        events.append({"rank": 0, "month": ISO[ev_rng.randrange(12)], "fixtures": " + ".join(combo),
                       "peak_lpm": round(peak, 1), "duration_min": ev_rng.choice([2, 3, 4, 5, 6, 8])})
    events.sort(key=lambda e: -e["peak_lpm"])
    for k, e in enumerate(events, 1):
        e["rank"] = k
    p95 = round(sorted(e["peak_lpm"] for e in events)[int(0.7 * len(events))], 1)

    zones = []
    growing = {g.id: g for g in home.cover if g.kind == "growing"}
    for zid, d in SOILS[sid].items():
        g = growing.get(zid)
        q = home.zone_quality[zid]
        zones.append({"zone": zid, "label": g.label if g else "Shared-garden allocation (common property)",
                      "area_m2": round(g.area, 1) if g else home.shared_allocation_m2,
                      "texture": d["texture"], "ph_water": d["ph"], "ec_ds_m": d["ec"],
                      "organic_carbon_pct": d["oc"], "nitrate_n_mg_kg": d["no3"], "colwell_p_mg_kg": d["p"],
                      "rooting_depth_cm": d["depth"], "sun_hours_summer": d["sun_s"], "sun_hours_winter": d["sun_w"],
                      "relative_productivity": q,
                      "productivity_class": "A" if q >= 0.9 else "B" if q >= 0.75 else "C" if q >= 0.6 else "D",
                      "note": d["note"]})

    quality = []
    for i, src, turb, ecoli, hard, tds, ph, fe, note in QUALITY[sid]:
        quality.append({"month": ISO[i], "source": src, "turbidity_ntu": turb, "e_coli_mpn_100ml": ecoli,
                        "hardness_mg_l_caco3": hard, "tds_mg_l": tds, "ph": ph, "iron_mg_l": fe, "note": note})

    harvest = round(r["fresh_kg"])
    summary = {
        "rain_mm": round(sum(x["rain_mm"] for x in months)),
        "rain_mean_mm": round(sum(sc.mean_climate(sid).rain)),
        "roof_inflow_kl": round(sum(x["roof_inflow_kl"] for x in months), 1),
        "overflow_kl": round(sum(x["overflow_kl"] for x in months), 1),
        "indoor_kl": round(sum(x["indoor_kl"] for x in months), 1),
        "indoor_l_person_day": round(sum(x["indoor_kl"] for x in months) * 1000 / 4 / 366, 1),
        "imported_kl": round(sum(x["imported_kl"] for x in months), 1),
        "bore_kl": round(sum(x["bore_kl"] for x in months), 1),
        "garden_applied_kl": round(sum(x["garden_applied_kl"] for x in months), 1),
        "garden_unmet_kl": round(sum(x["garden_unmet_estimate_kl"] for x in months), 1),
        "pump_kwh": round(sum(x["pump_kwh"] for x in months)),
        "runoff_coefficient": round(runoff_coeff, 2) if runoff_coeff else None,
        "connected_roof_m2": connected,
        "harvest_kg": harvest,
        "food_waste_kg_week": round(weekly, 1),
        "food_waste_kg_year": round(weekly * 52),
        "plant_share": round(sum(x[1] for x in fw) / sum(x[0] for x in fw), 2),
        "frost_nights": sum(x["frost_nights"] for x in months),
        "static_lift_m": lift,
        "peak_flow_lpm": events[0]["peak_lpm"],
        "p70_event_lpm": p95,
        "months_empty": sum(1 for x in months if x["tank_end_kl"] < 0.5),
    }
    need = sum(x["garden_applied_kl"] + x["garden_unmet_estimate_kl"] for x in months)
    pshare = round(100 * sum(x["garden_applied_kl"] for x in months) / need) if need else 100
    full = ["April", "May", "June", "July", "August", "September", "October", "November", "December",
            "January", "February", "March"]

    def run_text(flags):
        """Name the months flagged, as one circular run where possible."""
        idx = [i for i in range(12) if flags[i]]
        if not idx:
            return "no month"
        if len(idx) == 12:
            return "every month"
        start = next(i for i in range(12) if flags[i] and not flags[i - 1])
        run = []
        i = start
        while flags[i % 12] and len(run) < 12:
            run.append(i % 12)
            i += 1
        if len(run) == len(idx):
            if len(run) == 1:
                return full[run[0]]
            if len(run) == 2:
                return f"{full[run[0]]} and {full[run[1]]}"
            return f"every month from {full[run[0]]} to {full[run[-1]]}"
        return ", ".join(full[i] for i in idx[:-1]) + " and " + full[idx[-1]]
    implications = [t.format(frost=summary["frost_nights"], loads=math.ceil(summary["imported_kl"] / 12),
                             pshare=pshare,
                             empty_run=run_text([x["tank_end_kl"] < 0.5 for x in months]),
                             over_kl=round(summary["overflow_kl"]),
                             over_run=run_text([x["overflow_kl"] > 0.5 for x in months]),
                             cart_run=run_text([x["imported_kl"] > 0.5 for x in months]))
                    for t in IMPLICATIONS[sid]]
    return {
        "sid": sid, "slug": home.slug, "short": home.short, "family": home.family,
        "memo_date": MEMO_DATE, "year": YEAR_LABEL, "team": TEAM,
        "months": months, "summary": summary, "events": events, "zones": zones,
        "quality": quality, "food_waste": [{"week": AUDIT_WEEKS[k], "total_kg": a, "plant_kg": b,
                                             "meat_dairy_kg": c, "garden_kg": d} for k, (a, b, c, d) in enumerate(fw)],
        "hydraulics": {"tank_outlet_rl": hyd["tank_outlet_rl"], "highest_fixture": hyd["fixture"],
                       "highest_fixture_rl": hyd["fixture_rl"], "garden_high_rl": hyd["garden_high_rl"],
                       "static_lift_m": lift, "fixtures_lpm": fixtures, "served_now": hyd["served_now"],
                       "note": hyd["pressure_note"]},
        "costs": COSTS[sid], "implications": implications, "questions": QUESTIONS[sid],
        "missing": [{"month": ISO[i], "field": f_, "note": n} for i, f_, n in MISSING[sid]],
    }


MONTHLY_COLUMNS = [
    ("month", "", "Measured month, ISO year-month", "synthetic measured year"),
    ("days", "d", "Days in the month", "calendar"),
    ("rain_mm", "mm", "Rain at the on-site gauge", "synthetic measured year"),
    ("tmax_c", "°C", "Mean daily maximum air temperature", "synthetic measured year"),
    ("tmin_c", "°C", "Mean daily minimum air temperature", "synthetic measured year"),
    ("eto_mm", "mm", "Reference evapotranspiration, FAO-56 Hargreaves from the logged temperatures", "derived"),
    ("roof_inflow_kl", "kL", "Water reaching storage from the connected roof zones, from the tank balance", "derived"),
    ("overflow_kl", "kL", "Tank overflow, from the level logger at full", "derived"),
    ("tank_end_kl", "kL", "Stored volume at the end of the month, all existing tanks", "synthetic measured year"),
    ("indoor_kl", "kL", "Total indoor use", "synthetic measured year"),
    ("toilet_kl", "kL", "Toilet flushing, from flow-trace disaggregation", "derived"),
    ("shower_basin_kl", "kL", "Showers, bath and basins", "derived"),
    ("laundry_kl", "kL", "Laundry", "derived"),
    ("kitchen_kl", "kL", "Kitchen sink, dishwasher, drinking and cooking", "derived"),
    ("other_kl", "kL", "Other indoor use and leaks", "derived"),
    ("indoor_from_tank_kl", "kL", "Indoor use supplied from the tanks", "synthetic measured year"),
    ("bore_kl", "kL", "Bore draw at the licence meter", "synthetic measured year"),
    ("imported_kl", "kL", "Mains water (Canberra, Brisbane, Adelaide) or carted water (Alice Springs, Darwin)", "synthetic measured year"),
    ("garden_applied_kl", "kL", "Irrigation water applied, all sources", "synthetic measured year"),
    ("garden_from_mains_kl", "kL", "Of which from the mains", "synthetic measured year"),
    ("garden_unmet_estimate_kl", "kL", "Irrigation the existing plantings needed but did not get, estimated from soil moisture and ETo", "derived"),
    ("pump_kwh", "kWh", "Electricity used by the existing pumps, from a plug-in or circuit meter", "synthetic measured year"),
    ("coldest_night_c", "°C", "Lowest air temperature recorded in the month", "synthetic measured year"),
    ("frost_nights", "nights", "Nights with the air temperature below 0 °C", "synthetic measured year"),
    ("quality_flag", "", "Data-quality note for the month, if any", "record"),
]


def write_csv(path, header_note, columns, rows):
    with open(path, "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow([f"# {header_note}"])
        w.writerow(columns)
        for r in rows:
            w.writerow([("" if r.get(c) is None else r.get(c)) for c in columns])


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    out = {"label": "SYNTHETIC CASE DATA. Generated by research/model/release_b.py. Not measurements.",
           "memo_date": MEMO_DATE, "year": YEAR_LABEL, "team": TEAM,
           "monthly_columns": [{"name": n, "unit": u, "meaning": m, "kind": k} for n, u, m, k in MONTHLY_COLUMNS],
           "homes": {}}
    for h in HOMES:
        d = run(h.sid)
        out["homes"][h.sid] = d
        folder = os.path.join(OUT_DIR, h.slug)
        os.makedirs(folder, exist_ok=True)
        tag = f"SYNTHETIC CASE DATA - SLOP4761 Release B, {h.short}, {YEAR_LABEL}. Generated, not measured."
        write_csv(os.path.join(folder, "SYNTHETIC-monthly.csv"), tag, [c[0] for c in MONTHLY_COLUMNS], d["months"])
        write_csv(os.path.join(folder, "SYNTHETIC-zones.csv"), tag,
                  ["zone", "label", "area_m2", "texture", "ph_water", "ec_ds_m", "organic_carbon_pct", "nitrate_n_mg_kg",
                   "colwell_p_mg_kg", "rooting_depth_cm", "sun_hours_summer", "sun_hours_winter",
                   "relative_productivity", "productivity_class", "note"], d["zones"])
        write_csv(os.path.join(folder, "SYNTHETIC-flow-events.csv"), tag,
                  ["rank", "month", "fixtures", "peak_lpm", "duration_min"], d["events"])
        write_csv(os.path.join(folder, "SYNTHETIC-water-quality.csv"), tag,
                  ["month", "source", "turbidity_ntu", "e_coli_mpn_100ml", "hardness_mg_l_caco3", "tds_mg_l", "ph", "iron_mg_l", "note"],
                  d["quality"])
        write_csv(os.path.join(folder, "SYNTHETIC-food-waste-audit.csv"), tag,
                  ["week", "total_kg", "plant_kg", "meat_dairy_kg", "garden_kg"], d["food_waste"])
        # Sourced long-term climate, kept in its own file so it is never mistaken for the measured year.
        base = sc.mean_climate(h.sid)
        c = sm.load_climate()[h.presets["station"]]
        with open(os.path.join(folder, f"BOM-long-term-{h.presets['station']}.csv"), "w", encoding="utf-8", newline="") as f:
            w = csv.writer(f)
            w.writerow([f"# SOURCED: Bureau of Meteorology, climate statistics for station {h.presets['station']} ({c['name']}), all years of record. ETo derived by FAO-56 Hargreaves."])
            w.writerow(["month", "rain_mm", "tmax_c", "tmin_c", "eto_mm", "effective_rain_mm"])
            for m in range(12):
                w.writerow([sc.MONTHS[m], base.rain[m], c["tmax"][m], c["tmin"][m], round(base.eto[m]), round(base.pe[m], 1)])
        s = d["summary"]
        print(f"{h.sid} {h.short:13} rain {s['rain_mm']} (mean {s['rain_mean_mm']})  inflow {s['roof_inflow_kl']}  "
              f"import {s['imported_kl']}  bore {s['bore_kl']}  garden {s['garden_applied_kl']}  "
              f"A={s['runoff_coefficient']}  indoor {s['indoor_l_person_day']} L/p/d  harvest {s['harvest_kg']} kg")
    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=1)
        f.write("\n")
    # The shared data dictionary.
    with open(os.path.join(OUT_DIR, "data-dictionary.csv"), "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["# SLOP4761 Release B data dictionary. 'synthetic measured year' values are generated case data, not measurements."])
        w.writerow(["file", "column", "unit", "meaning", "kind"])
        for n, u, m, k in MONTHLY_COLUMNS:
            w.writerow(["SYNTHETIC-monthly.csv", n, u, m, k])
        for n, u, m in [("zone", "", "Growing-zone id on the Release A plan"), ("area_m2", "m2", "Zone area from the plan"),
                        ("texture", "", "Field texture"), ("ph_water", "", "pH, 1:5 soil:water"),
                        ("ec_ds_m", "dS/m", "Electrical conductivity, 1:5"), ("organic_carbon_pct", "%", "Organic carbon, Walkley-Black"),
                        ("nitrate_n_mg_kg", "mg/kg", "Nitrate nitrogen"), ("colwell_p_mg_kg", "mg/kg", "Colwell phosphorus"),
                        ("rooting_depth_cm", "cm", "Depth to a restricting layer"), ("sun_hours_summer", "h/day", "Direct sun, December solstice"),
                        ("sun_hours_winter", "h/day", "Direct sun, June solstice"),
                        ("relative_productivity", "0-1", "Specialists' relative productivity of the zone against the best on the site"),
                        ("productivity_class", "", "A (0.9 or more), B (0.75), C (0.6), D (below 0.6)")]:
            w.writerow(["SYNTHETIC-zones.csv", n, u, m, "synthetic measured year"])
        for n, u, m in [("peak_lpm", "L/min", "Highest one-minute average flow in the event"), ("duration_min", "min", "Event duration"),
                        ("fixtures", "", "Fixtures identified from the flow signature")]:
            w.writerow(["SYNTHETIC-flow-events.csv", n, u, m, "synthetic measured year"])
        for n, u, m in [("turbidity_ntu", "NTU", "Turbidity"), ("e_coli_mpn_100ml", "MPN/100 mL", "E. coli, most probable number"),
                        ("hardness_mg_l_caco3", "mg/L as CaCO3", "Total hardness"), ("tds_mg_l", "mg/L", "Total dissolved solids"),
                        ("ph", "", "pH"), ("iron_mg_l", "mg/L", "Total iron")]:
            w.writerow(["SYNTHETIC-water-quality.csv", n, u, m, "synthetic measured year"])
        for n, u, m in [("total_kg", "kg/week", "All food waste in the audit week"), ("plant_kg", "kg/week", "Plant-based food waste"),
                        ("meat_dairy_kg", "kg/week", "Meat, fish and dairy"), ("garden_kg", "kg/week", "Garden trimmings, not food waste")]:
            w.writerow(["SYNTHETIC-food-waste-audit.csv", n, u, m, "synthetic measured year"])
        for n, u, m in [("rain_mm", "mm", "Long-term mean monthly rain"), ("eto_mm", "mm", "Hargreaves ETo from long-term mean temperatures"),
                        ("effective_rain_mm", "mm", "FAO effective rain from the mean monthly rain")]:
            w.writerow(["BOM-long-term-<station>.csv", n, u, m, "sourced (BoM); derived columns computed"])
    print(f"wrote {OUT_JSON} and CSVs under {OUT_DIR}")


if __name__ == "__main__":
    main()
